wandb_version: 1

architecture:
  desc: null
  value: Multi_View Encoder
dataset:
  desc: null
  value: 'ArgoCL : Train1'
epochs:
  desc: null
  value: 30
_wandb:
  desc: null
  value:
    python_version: 3.10.6
    cli_version: 0.15.4
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: true
    start_time: 1686907638.275378
    t:
      1:
      - 1
      - 41
      - 49
      - 55
      - 63
      2:
      - 1
      - 41
      - 49
      - 55
      - 63
      3:
      - 16
      - 23
      4: 3.10.6
      5: 0.15.4
      8:
      - 1
      - 2
      - 5
